### ISSUE TITLE
[BUG] Crashing on iOS Godot 3.2.2

### ISSUE THREAD

**Issue by martinpelli** [Poing-Studios/Godot-AdMob-Android-iOS#44] opened 2021-01-17 19:51 UTC
I tested the plugin on iOS in my iPhone 8 Plus with Godot 3.2.3 and the 3.2.3 template and is working, but Godot 3.2.3 has a huge bug with buttons delay and my game is unplayable

So tried exporting my game with Godot 3.2.2 and works perfectly, but adding the plugin with the 3.2.2 template it is crashing with the next log.
```
2021-01-17 16:47:42.033876-0300 frichen[501:26981] Godot Engine v3.2.2.stable.custom_build - https://godotengine.org
2021-01-17 16:47:42.034215-0300 frichen[501:27193]  - <Google>[I-ACS025031] AdMob App ID changed. Original, new: (nil), ca-app-pub-9081047336041164~6080891688
2021-01-17 16:47:42.034855-0300 frichen[501:27199]  - <Google>[I-ACS023007] Analytics v.70100000 started
2021-01-17 16:47:42.035029-0300 frichen[501:27199]  - <Google>[I-ACS023008] To enable debug logging set the following application argument: -APMAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
2021-01-17 16:47:42.041920-0300 frichen[501:27194]  - <Google>[I-ACS023171] Resetting App Measurement data
2021-01-17 16:47:42.043417-0300 frichen[501:26981] OpenGL ES 3.0 Renderer: Apple A11 GPU
2021-01-17 16:47:42.045867-0300 frichen[501:26981] fopen failed for data file: errno = 2 (No such file or directory)
2021-01-17 16:47:42.045929-0300 frichen[501:26981] Errors found! Invalidating cache...
2021-01-17 16:47:42.054845-0300 frichen[501:27195]  - <Google>[I-ACS023014] Failed to delete old database file. Error: Error Domain=NSCocoaErrorDomain Code=4 "“google-app-measurement.sql” couldn’t be removed." UserInfo={NSUserStringVariant=(
    Remove
), NSFilePath=/var/mobile/Containers/Data/Application/ECD1206A-2FE3-4B36-94E8-8B91A28C0551/Library/Application Support/Google/Measurement/google-app-measurement.sql, NSUnderlyingError=0x282394b10 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
2021-01-17 16:47:42.580870-0300 frichen[501:26981] 
2021-01-17 16:47:42.701920-0300 frichen[501:27195]  - <Google>[I-ACS800023] No pending snapshot to activate. SDK name: app_measurement
2021-01-17 16:47:42.818680-0300 frichen[501:27198]  - <Google>[I-ACS023012] Analytics collection enabled
2021-01-17 16:47:42.870302-0300 frichen[501:26981] fopen failed for data file: errno = 2 (No such file or directory)
2021-01-17 16:47:42.870404-0300 frichen[501:26981] Errors found! Invalidating cache...
2021-01-17 16:47:42.875134-0300 frichen[501:26981] fopen failed for data file: errno = 2 (No such file or directory)
2021-01-17 16:47:42.875183-0300 frichen[501:26981] Errors found! Invalidating cache...
2021-01-17 16:47:43.131771-0300 frichen[501:26981] -[__NSCFString containsObject:]: unrecognized selector sent to instance 0x2838d4400
2021-01-17 16:47:43.142919-0300 frichen[501:26981] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString containsObject:]: unrecognized selector sent to instance 0x2838d4400'
*** First throw call stack:
(0x1970029d8 0x1ab36bb54 0x196f12bbc 0x19700501c 0x197006f8c 0x102e6afd8 0x102e6d5dc 0x105251528 0x105252e6c 0x102e6bfd0 0x10302b558 0x103e9798c 0x103133b70 0x19a1388e4 0x19a20ae04 0x196f5fb54 0x196f83420 0x196f82834 0x196f7c9f4 0x196f7bba0 0x1adcb9598 0x19986b3d8 0x199870958 0x102ffde80)
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString containsObject:]: unrecognized selector sent to instance 0x2838d4400'
terminating with uncaught exception of type NSException
(lldb) 
```

**Comment by gustavottc** [comment] 2021-01-17 20:20
The delay with 3.2.3 version was with AdMob buttons or your game?

**Comment by martinpelli** [comment] 2021-01-17 20:21
@gustavottc is a bug from godot, https://github.com/godotengine/godot/issues/42164

**Comment by gustavottc** [comment] 2021-01-17 20:30
Try to set to ```false``` ```is_test_europe_user_consent``` and send me please again the log

**Comment by martinpelli** [comment] 2021-01-17 20:44
@gustavottc and where is that? In my godot prject on the admob gscript I dont have that variable

**Comment by gustavottc** [comment] 2021-01-17 20:46
Probably you need to update here: https://github.com/Poing-Studios/Godot-AdMob-Android-iOS/tree/master/admob_api

Please consider testing with example project: https://github.com/Poing-Studios/Godot-AdMob-Android-iOS/tree/master/example

**Comment by gustavottc** [comment] 2021-01-17 20:47
[libgodot.iphone.opt.arm64.a.zip](https://github.com/Poing-Studios/Godot-AdMob-Android-iOS/files/5826808/libgodot.iphone.opt.arm64.a.zip)


I did a update, please use this '.a' file for 3.2.2 (only works on real devices with arch64)

**Comment by martinpelli** [comment] 2021-01-17 21:09
@gustavottc I added the var is_test_europe_user_consent, set it to false, change the .a file for that one that you mentioned and is working now! thanks for your help!

I would also like to know if there is any possibility that the tracking identifier poster that the user has to accept to see ads, is it possible to show it when the ads are about to be shown?, Because, in my case you open the game and the poster is open up and say if you agree to be tracked

**Comment by gustavottc** [comment] 2021-01-17 21:20
Nice! 

The user doesn't need to accept to show the ads, at least I believe not, I already selected for Track and Not Track and the result was the same with test ads, so with real ads should work too

**Comment by gustavottc** [comment] 2021-01-17 21:21
please now test with "is_test_europe_user_consent" with ```true``` value, and check if UMP will appear, if it's appearing so your app should work 100% fine with AdMob

**Comment by martinpelli** [comment] 2021-01-17 21:30
@gustavottc ohh nice.
 Whats is UMP 😢😢

**Comment by gustavottc** [comment] 2021-01-17 21:37
You can check here: https://developers.google.com/admob/ump/ios/quick-start#introduction

This is only required if you are publishing your app to Europe if your app doesn't have this and have ads, he can be banned on Europe temporary until you put it (it's hard to this happen, but we don't want it)

**Comment by martinpelli** [comment] 2021-01-17 21:57
@gustavottc so You mean if this is showing 
![image](https://user-images.githubusercontent.com/63437171/104857199-89f99880-58f5-11eb-999b-dfc18610ad4e.png)

because this is appearing on my game with is_test_europe_user_consent = true

**Comment by gustavottc** [comment] 2021-01-17 21:58
I mean this

![Captura de Tela 2021-01-17 às 14 41 27](https://user-images.githubusercontent.com/20030153/104857260-f4aad400-58f5-11eb-8caf-42f68a840d92.png)

**Comment by martinpelli** [comment] 2021-01-17 23:07
@gustavottc  Is not working, I don't know if I am doing something wrong, ads are still working. I added the app to active on founding choices

2021-01-17 20:02:07.864392-0300 frichen[725:103874]  - <Google>[I-ACS800023] No pending snapshot to activate. SDK name: app_measurement
2021-01-17 20:02:08.064573-0300 frichen[725:103819]  - <Google>[I-ACS023012] Analytics collection enabled
2021-01-17 20:02:08.296017-0300 frichen[725:103822]  - <Google>[I-ACS025041] Discarding empty consent settings
2021-01-17 20:02:08.323714-0300 frichen[725:103508] BEFORE adapterStatusesByClassName
2021-01-17 20:02:08.323810-0300 frichen[725:103508] AFTER adapterStatusesByClassName
2021-01-17 20:02:08.323835-0300 frichen[725:103508] BEFORE states
2021-01-17 20:02:08.323858-0300 frichen[725:103508] AFTER states
2021-01-17 20:02:08.323882-0300 frichen[725:103508] GADMobileAds : 1
2021-01-17 20:02:13.899847-0300 frichen[725:103823]  - <Google>[I-ACS012056] Transaction failed. Transaction failed

**Comment by martinpelli** [comment] 2021-01-17 23:09
@gustavottc or maybe I cannot see it because I am not from europe???

**Comment by gustavottc** [comment] 2021-01-17 23:12
@martinpelli , no i'm at Brazil and it's working, hmmm, are you trying with example project?

**Comment by martinpelli** [comment] 2021-01-17 23:28
@gustavottc yes, with both ads work but not the UMP. On example project I exported without changing anything. I only change the xcode parameters mentioned on installation. For UMP I only set to active the founding choices is there anything else that I am forgetting?

**Comment by gustavottc** [comment] 2021-01-17 23:29
also be sure to mark ```is_for_child_directed_treatment``` = ```false```

**Comment by gustavottc** [comment] 2021-01-17 23:30
@martinpelli probably only this parameter ```is_for_child_direct_treatment```

**Comment by martinpelli** [comment] 2021-01-17 23:31
@gustavottc yes it is setted false by default when downloading the example project

**Comment by gustavottc** [comment] 2021-01-17 23:43
[libgodot.iphone.opt.arm64.a.zip](https://github.com/Poing-Studios/Godot-AdMob-Android-iOS/files/5827029/libgodot.iphone.opt.arm64.a.zip)

Please try with this '.a', i added some NSLogs to see the cause of this

**Comment by martinpelli** [comment] 2021-01-17 23:59
@gustavottc 

```
<Google>[I-ACS023014] Failed to delete old database file. Error: Error Domain=NSCocoaErrorDomain Code=4 "“google-app-measurement.sql” couldn’t be removed." UserInfo={NSUserStringVariant=(
    Remove
), NSFilePath=/var/mobile/Containers/Data/Application/E6C88F6D-DF32-4160-AED6-A3C66E981F86/Library/Application Support/Google/Measurement/google-app-measurement.sql, NSUnderlyingError=0x283fc1740 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
2021-01-17 20:57:20.046514-0300 AdMob[846:127632] 
2021-01-17 20:57:20.338369-0300 AdMob[846:127882]  - <Google>[I-ACS800023] No pending snapshot to activate. SDK name: app_measurement
2021-01-17 20:57:20.342842-0300 AdMob[846:127632] Testing the UMP
2021-01-17 20:57:20.356439-0300 AdMob[846:127632] <UMP SDK> To enable debug mode for this device, set: UMPDebugSettings.testDeviceIdentifiers = @[ @"C5C9EAFE-D567-4282-843E-9EBDEB1E72A9" ];
2021-01-17 20:57:20.984891-0300 AdMob[846:127879]  - <Google>[I-ACS023012] Analytics collection enabled
2021-01-17 20:57:21.137633-0300 AdMob[846:127632] _on_AdMob_consent_info_update_success: Consent Form not Available
2021-01-17 20:57:21.144245-0300 AdMob[846:127632] on Testing Real Device: testDeviceIdentifiers: 90f7919cddb2c8aafb74a42365fa9eed
2021-01-17 20:57:21.145397-0300 AdMob[846:127632] maxAdContentRating = GADMaxAdContentRatingGeneral
******** stop animation!
2021-01-17 20:57:21.666695-0300 AdMob[846:127891]  - <Google>[I-ACS012056] Transaction failed. Transaction failed
2021-01-17 20:57:22.172414-0300 AdMob[846:127632] [Error] _authenticateUsingAlert:Failed to authenticate player with existing credentials.Error: Error Domain=GKErrorDomain Code=15 "No se pudo realizar la operación solicitada porque Game Center no reconoce esta aplicación." UserInfo={GKServerStatusCode=5019, NSLocalizedDescription=No se pudo realizar la operación solicitada porque Game Center no reconoce esta aplicación., NSUnderlyingError=0x283f9d260 {Error Domain=GKServerErrorDomain Code=5019 "status = 5019, no game matching descriptor: ios:studios.poing.admob:1.0:1.0+-1" UserInfo={GKServerStatusCode=5019, NSLocalizedFailureReason=status = 5019, no game matching descriptor: ios:studios.poing.admob:1.0:1.0+-1}}}
2021-01-17 20:57:22.192352-0300 AdMob[846:127632] [Account Error] startAuthenticationForExistingPrimaryPlayer:Failed to Authenticate player.Error: Error Domain=GKErrorDomain Code=15 "No se pudo realizar la operación solicitada porque Game Center no reconoce esta aplicación." UserInfo={NSLocalizedDescription=No se pudo realizar la operación solicitada porque Game Center no reconoce esta aplicación.}
start animation!
2021-01-17 20:57:25.822427-0300 AdMob[846:127632] WF: === Starting WebFilter logging for process AdMob
2021-01-17 20:57:25.822693-0300 AdMob[846:127632] WF: _userSettingsForUser mobile: {
    filterBlacklist =     (
    );
    filterWhitelist =     (
    );
    restrictWeb = 1;
    useContentFilter = 0;
    useContentFilterOverrides = 0;
    whitelistEnabled = 0;
}
2021-01-17 20:57:25.822944-0300 AdMob[846:127632] WF: _WebFilterIsActive returning: NO
2021-01-17 20:57:26.544451-0300 AdMob[846:128111]  - <Google>[I-ACS025041] Discarding empty consent settings
2021-01-17 20:57:26.568464-0300 AdMob[846:127632] BEFORE adapterStatusesByClassName
2021-01-17 20:57:26.568520-0300 AdMob[846:127632] AFTER adapterStatusesByClassName
2021-01-17 20:57:26.568541-0300 AdMob[846:127632] BEFORE states
2021-01-17 20:57:26.568561-0300 AdMob[846:127632] AFTER states
2021-01-17 20:57:26.568581-0300 AdMob[846:127632] GADMobileAds : 1
2021-01-17 20:57:26.578255-0300 AdMob[846:127632] Calling load_interstitial
2021-01-17 20:57:26.578302-0300 AdMob[846:127632] interstitial will load with the id
2021-01-17 20:57:26.578328-0300 AdMob[846:127632] ca-app-pub-3940256099942544/4411468910
2021-01-17 20:57:26.578403-0300 AdMob[846:127632] interstitial created with the id
2021-01-17 20:57:26.578425-0300 AdMob[846:127632] ca-app-pub-3940256099942544/4411468910
2021-01-17 20:57:26.581621-0300 AdMob[846:127632] Calling load_rewarded
2021-01-17 20:57:26.581655-0300 AdMob[846:127632] rewarded will load with the id
2021-01-17 20:57:26.581676-0300 AdMob[846:127632] ca-app-pub-3940256099942544/1712485313
2021-01-17 20:57:26.582053-0300 AdMob[846:127632] rewarded created with the id
2021-01-17 20:57:26.582079-0300 AdMob[846:127632] ca-app-pub-3940256099942544/1712485313
2021-01-17 20:57:27.377865-0300 AdMob[846:128111] <Google> Cannot find an ad network adapter with the name(s): com.google.DummyAdapter. Remember to link all required ad network adapters and SDKs, and set -ObjC in the 'Other Linker Flags' setting of your build target.
```

**Comment by gustavottc** [comment] 2021-01-18 00:05
What's the value of your ```GADApplicationIdentifier``` into ```.plist```?

**Comment by martinpelli** [comment] 2021-01-18 00:06
@gustavottc the id of my app on AdMob

**Comment by gustavottc** [comment] 2021-01-18 00:06
Also: ```and set -ObjC in the 'Other Linker Flags' setting of your build target.```

**Comment by gustavottc** [comment] 2021-01-18 00:08
> @gustavottc the id of my app on AdMob

The UMP will only appear with your id-app if you setup Funding Choices: https://support.google.com/fundingchoices/answer/9180084

**Comment by martinpelli** [comment] 2021-01-18 00:09
@gustavottc yes I dont know why is telling me to set -ObjC in the 'Other Linker Flags' setting of your build target, I already set it
![image](https://user-images.githubusercontent.com/63437171/104860060-32b0f380-5908-11eb-9956-8ec9ecf2e1c4.png)

**Comment by gustavottc** [comment] 2021-01-18 00:12
No problem, i think this is not related with UMP because it was logged after the UMP Logs, think the problem is with ```GADApplicationIdentifier```

**Comment by martinpelli** [comment] 2021-01-18 00:13
![image](https://user-images.githubusercontent.com/63437171/104860124-8de2e600-5908-11eb-9d20-7ca3e92c3ab7.png)
![image](https://user-images.githubusercontent.com/63437171/104860159-cedafa80-5908-11eb-9c58-ecda0917f76c.png)

@gustavottc

**Comment by gustavottc** [comment] 2021-01-18 00:18
if you create now it can take some time do work like 10 minutes, it's recommended use the test id: ```ca-app-pub-3940256099942544~1458002511``` if doesn't work with test id so probably won't work with yours

**Comment by martinpelli** [comment] 2021-01-18 01:21
@gustavottc not working with test id and I have the same errors

```
2021-01-17 22:19:13.161561-0300 AdMob[1016:167144] Godot Engine v3.2.2.stable.custom_build - https://godotengine.org
2021-01-17 22:19:13.164444-0300 AdMob[1016:167371]  - <Google>[I-ACS025031] AdMob App ID changed. Original, new: (nil), ca-app-pub-3940256099942544~1458002511
2021-01-17 22:19:13.164863-0300 AdMob[1016:167371]  - <Google>[I-ACS023007] Analytics v.70100000 started
2021-01-17 22:19:13.165459-0300 AdMob[1016:167371]  - <Google>[I-ACS023008] To enable debug logging set the following application argument: -APMAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
2021-01-17 22:19:13.166982-0300 AdMob[1016:167371]  - <Google>[I-ACS023171] Resetting App Measurement data
2021-01-17 22:19:13.168553-0300 AdMob[1016:167144] OpenGL ES 2.0 Renderer: Apple A11 GPU
2021-01-17 22:19:13.169966-0300 AdMob[1016:167144] fopen failed for data file: errno = 2 (No such file or directory)
2021-01-17 22:19:13.170011-0300 AdMob[1016:167144] Errors found! Invalidating cache...
2021-01-17 22:19:13.210372-0300 AdMob[1016:167144] fopen failed for data file: errno = 2 (No such file or directory)
2021-01-17 22:19:13.210446-0300 AdMob[1016:167144] Errors found! Invalidating cache...
2021-01-17 22:19:13.215450-0300 AdMob[1016:167144] fopen failed for data file: errno = 2 (No such file or directory)
2021-01-17 22:19:13.215507-0300 AdMob[1016:167144] Errors found! Invalidating cache...
2021-01-17 22:19:13.218038-0300 AdMob[1016:167144] OpenGL ES 2.0 Batching: ON
2021-01-17 22:19:13.415673-0300 AdMob[1016:167371]  - <Google>[I-ACS023014] Failed to delete old database file. Error: Error Domain=NSCocoaErrorDomain Code=4 "“google-app-measurement.sql” couldn’t be removed." UserInfo={NSUserStringVariant=(
    Remove
), NSFilePath=/var/mobile/Containers/Data/Application/AF1FDE78-F7FB-42EF-9A6B-43AE6EF0F470/Library/Application Support/Google/Measurement/google-app-measurement.sql, NSUnderlyingError=0x2823f18f0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
2021-01-17 22:19:13.685735-0300 AdMob[1016:167144] 
2021-01-17 22:19:13.962366-0300 AdMob[1016:167369]  - <Google>[I-ACS800023] No pending snapshot to activate. SDK name: app_measurement
2021-01-17 22:19:13.980284-0300 AdMob[1016:167144] Testing the UMP
2021-01-17 22:19:13.995214-0300 AdMob[1016:167144] <UMP SDK> To enable debug mode for this device, set: UMPDebugSettings.testDeviceIdentifiers = @[ @"C5C9EAFE-D567-4282-843E-9EBDEB1E72A9" ];
2021-01-17 22:19:14.566688-0300 AdMob[1016:167371]  - <Google>[I-ACS023012] Analytics collection enabled
2021-01-17 22:19:14.696382-0300 AdMob[1016:167144] _on_AdMob_consent_info_update_success: Consent Form not Available
2021-01-17 22:19:14.702054-0300 AdMob[1016:167144] on Testing Real Device: testDeviceIdentifiers: 90f7919cddb2c8aafb74a42365fa9eed
2021-01-17 22:19:14.703337-0300 AdMob[1016:167144] maxAdContentRating = GADMaxAdContentRatingGeneral
******** stop animation!
2021-01-17 22:19:14.812749-0300 AdMob[1016:167144] [Error] _authenticateUsingAlert:Failed to authenticate player with existing credentials.Error: Error Domain=GKErrorDomain Code=15 "No se pudo realizar la operación solicitada porque Game Center no reconoce esta aplicación." UserInfo={GKServerStatusCode=5019, NSLocalizedDescription=No se pudo realizar la operación solicitada porque Game Center no reconoce esta aplicación., NSUnderlyingError=0x2822ce190 {Error Domain=GKServerErrorDomain Code=5019 "status = 5019, no game matching descriptor: ios:studios.poing.admob:1.0:1.0+-1" UserInfo={GKServerStatusCode=5019, NSLocalizedFailureReason=status = 5019, no game matching descriptor: ios:studios.poing.admob:1.0:1.0+-1}}}
2021-01-17 22:19:14.826098-0300 AdMob[1016:167144] [Account Error] startAuthenticationForExistingPrimaryPlayer:Failed to Authenticate player.Error: Error Domain=GKErrorDomain Code=15 "No se pudo realizar la operación solicitada porque Game Center no reconoce esta aplicación." UserInfo={NSLocalizedDescription=No se pudo realizar la operación solicitada porque Game Center no reconoce esta aplicación.}
2021-01-17 22:19:15.468735-0300 AdMob[1016:167390]  - <Google>[I-ACS023130] Configuration not found. Using default configuration

```

**Comment by gustavottc** [comment] 2021-01-18 01:23
Oh, i just saw now: ```<UMP SDK> To enable debug mode for this device, set: UMPDebugSettings.testDeviceIdentifiers = @[ @"C5C9EAFE-D567-4282-843E-9EBDEB1E72A9" ];```

I need to do some changes

**Comment by gustavottc** [comment] 2021-01-18 01:32
[libgodot.iphone.opt.arm64.a.zip](https://github.com/Poing-Studios/Godot-AdMob-Android-iOS/files/5827251/libgodot.iphone.opt.arm64.a.zip)

Try with this '.a', please send again the log if possible

**Comment by martinpelli** [comment] 2021-01-18 02:09
@gustavottc **Is working now!!**

```
2021-01-17 23:07:04.910576-0300 AdMob[1111:192563] Godot Engine v3.2.2.stable.custom_build - https://godotengine.org
2021-01-17 23:07:04.921839-0300 AdMob[1111:192563] OpenGL ES 2.0 Renderer: Apple A11 GPU
2021-01-17 23:07:04.926307-0300 AdMob[1111:192563] fopen failed for data file: errno = 2 (No such file or directory)
2021-01-17 23:07:04.926427-0300 AdMob[1111:192563] Errors found! Invalidating cache...
2021-01-17 23:07:05.018721-0300 AdMob[1111:192563] fopen failed for data file: errno = 2 (No such file or directory)
2021-01-17 23:07:05.018794-0300 AdMob[1111:192563] Errors found! Invalidating cache...
2021-01-17 23:07:05.029580-0300 AdMob[1111:192563] fopen failed for data file: errno = 2 (No such file or directory)
2021-01-17 23:07:05.029649-0300 AdMob[1111:192563] Errors found! Invalidating cache...
2021-01-17 23:07:05.033887-0300 AdMob[1111:192563] OpenGL ES 2.0 Batching: ON
2021-01-17 23:07:05.256378-0300 AdMob[1111:192873]  - <Google>[I-ACS023014] Failed to delete old database file. Error: Error Domain=NSCocoaErrorDomain Code=4 "“google-app-measurement.sql” couldn’t be removed." UserInfo={NSUserStringVariant=(
    Remove
), NSFilePath=/var/mobile/Containers/Data/Application/534C90F0-AC82-43A5-9A43-E21D348B3696/Library/Application Support/Google/Measurement/google-app-measurement.sql, NSUnderlyingError=0x280154d50 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
2021-01-17 23:07:06.050270-0300 AdMob[1111:192563] 
2021-01-17 23:07:06.397191-0300 AdMob[1111:192563] Testing the UMP
2021-01-17 23:07:06.398430-0300 AdMob[1111:192563] UUID: A\M-ij\M-p\M-!!
2021-01-17 23:07:06.401733-0300 AdMob[1111:192563] device ID: A\M-ij\M-p\M-!!
2021-01-17 23:07:07.701342-0300 AdMob[1111:192563] [Error] _authenticateUsingAlert:Failed to authenticate player with existing credentials.Error: Error Domain=GKErrorDomain Code=15 "No se pudo realizar la operación solicitada porque Game Center no reconoce esta aplicación." UserInfo={GKServerStatusCode=5019, NSLocalizedDescription=No se pudo realizar la operación solicitada porque Game Center no reconoce esta aplicación., NSUnderlyingError=0x2801555f0 {Error Domain=GKServerErrorDomain Code=5019 "status = 5019, no game matching descriptor: ios:studios.poing.admob:1.0:1.0+-1" UserInfo={GKServerStatusCode=5019, NSLocalizedFailureReason=status = 5019, no game matching descriptor: ios:studios.poing.admob:1.0:1.0+-1}}}
2021-01-17 23:07:07.735919-0300 AdMob[1111:192563] [Account Error] startAuthenticationForExistingPrimaryPlayer:Failed to Authenticate player.Error: Error Domain=GKErrorDomain Code=15 "No se pudo realizar la operación solicitada porque Game Center no reconoce esta aplicación." UserInfo={NSLocalizedDescription=No se pudo realizar la operación solicitada porque Game Center no reconoce esta aplicación.}
2021-01-17 23:07:07.857669-0300 AdMob[1111:192872]  - <Google>[I-ACS800023] No pending snapshot to activate. SDK name: app_measurement
2021-01-17 23:07:08.014006-0300 AdMob[1111:192563] _on_AdMob_consent_info_update_success: Consent Form Available
2021-01-17 23:07:08.947156-0300 AdMob[1111:192869]  - <Google>[I-ACS023012] Analytics collection enabled
2021-01-17 23:07:09.301057-0300 AdMob[1111:192563] WF: === Starting WebFilter logging for process AdMob
2021-01-17 23:07:09.301252-0300 AdMob[1111:192563] WF: _userSettingsForUser mobile: {
    filterBlacklist =     (
    );
    filterWhitelist =     (
    );
    restrictWeb = 1;
    useContentFilter = 0;
    useContentFilterOverrides = 0;
    whitelistEnabled = 0;
}
2021-01-17 23:07:09.301511-0300 AdMob[1111:192563] WF: _WebFilterIsActive returning: NO
2021-01-17 23:07:09.837192-0300 AdMob[1111:192563] _on_AdMob_consent_status_changed User consent required but not yet obtained.:
*********** did receive memory warning!
2021-01-17 23:07:10.590560-0300 AdMob[1111:192563] Received memory pressure event 4 vm pressure 1

Received memory pressure event 4 vm pressure 1
2021-01-17 23:07:17.381146-0300 AdMob[1111:192563] _on_AdMob_consent_form_dismissed
2021-01-17 23:07:17.381483-0300 AdMob[1111:192563] _on_AdMob_consent_status_changed: User consent obtained. Personalization not defined
2021-01-17 23:07:17.392686-0300 AdMob[1111:192563] on Testing Real Device: testDeviceIdentifiers: 90f7919cddb2c8aafb74a42365fa9eed
2021-01-17 23:07:17.394466-0300 AdMob[1111:192563] maxAdContentRating = GADMaxAdContentRatingGeneral
******** stop animation!
2021-01-17 23:07:18.240073-0300 AdMob[1111:193132]  - <Google>[I-ACS023130] Configuration not found. Using default configuration
2021-01-17 23:07:18.666479-0300 AdMob[1111:192563] WF: _userSettingsForUser mobile: {
    filterBlacklist =     (
    );
    filterWhitelist =     (
    );
    restrictWeb = 1;
    useContentFilter = 0;
    useContentFilterOverrides = 0;
    whitelistEnabled = 0;
}
2021-01-17 23:07:18.666558-0300 AdMob[1111:192563] WF: _WebFilterIsActive returning: NO
start animation!
2021-01-17 23:07:19.285587-0300 AdMob[1111:192872]  - <Google>[I-ACS025041] Discarding empty consent settings
2021-01-17 23:07:19.316190-0300 AdMob[1111:192563] BEFORE adapterStatusesByClassName
2021-01-17 23:07:19.316244-0300 AdMob[1111:192563] AFTER adapterStatusesByClassName
2021-01-17 23:07:19.316265-0300 AdMob[1111:192563] BEFORE states
2021-01-17 23:07:19.316288-0300 AdMob[1111:192563] AFTER states
2021-01-17 23:07:19.316311-0300 AdMob[1111:192563] GADMobileAds : 1
2021-01-17 23:07:19.319827-0300 AdMob[1111:192563] Calling load_interstitial
2021-01-17 23:07:19.319871-0300 AdMob[1111:192563] interstitial will load with the id
2021-01-17 23:07:19.319891-0300 AdMob[1111:192563] ca-app-pub-3940256099942544/4411468910
2021-01-17 23:07:19.319976-0300 AdMob[1111:192563] interstitial created with the id
2021-01-17 23:07:19.320000-0300 AdMob[1111:192563] ca-app-pub-3940256099942544/4411468910
2021-01-17 23:07:19.323054-0300 AdMob[1111:192563] Calling load_rewarded
2021-01-17 23:07:19.323101-0300 AdMob[1111:192563] rewarded will load with the id
2021-01-17 23:07:19.323128-0300 AdMob[1111:192563] ca-app-pub-3940256099942544/1712485313
2021-01-17 23:07:19.323465-0300 AdMob[1111:192563] rewarded created with the id
2021-01-17 23:07:19.323494-0300 AdMob[1111:192563] ca-app-pub-3940256099942544/1712485313
2021-01-17 23:07:20.240322-0300 AdMob[1111:192563] WF: _userSettingsForUser mobile: {
    filterBlacklist =     (
    );
    filterWhitelist =     (
    );
    restrictWeb = 1;
    useContentFilter = 0;
    useContentFilterOverrides = 0;
    whitelistEnabled = 0;
}
2021-01-17 23:07:20.240376-0300 AdMob[1111:192563] WF: _WebFilterIsActive returning: NO
2021-01-17 23:07:20.243489-0300 AdMob[1111:192872] <Google> Cannot find an ad network adapter with the name(s): com.google.DummyAdapter. Remember to link all required ad network adapters and SDKs, and set -ObjC in the 'Other Linker Flags' setting of your build target.
2021-01-17 23:07:20.270728-0300 AdMob[1111:192563] error while creating reward
2021-01-17 23:07:20.821587-0300 AdMob[1111:192563] interstitialDidReceiveAd
*********** did receive memory warning!
2021-01-17 23:07:23.420972-0300 AdMob[1111:192563] Received memory pressure event 2 vm pressure 0

Received memory pressure event 2 vm pressure 0
2021-01-17 23:07:47.378183-0300 AdMob[1111:192563] Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
2021-01-17 23:07:47.393189-0300 AdMob[1111:192563] Could not signal service com.apple.WebKit.Networking: 113: Could not find specified service
```

**Comment by gustavottc** [comment] 2021-01-18 02:17
@martinpelli nice!!! the form of UMP is appearing now?

do you alter these parts?

```
2021-01-17 23:07:06.398430-0300 AdMob[1111:192563] UUID: A\M-ij\M-p\M-!!
2021-01-17 23:07:06.401733-0300 AdMob[1111:192563] device ID: A\M-ij\M-p\M-!!
```

if yes, the result of they was the same?

**Comment by martinpelli** [comment] 2021-01-18 03:21
@gustavottc no, I copy and paste the log. The ump is appearing on both, example and my game

**Comment by gustavottc** [comment] 2021-01-18 12:32
Nice, so i will close this issue since everything seems fixed, thanks!

**Closed by gustavottc** 2021-01-18 12:32 UTC
Labels: bug

**Comment by martinpelli** [comment] 2021-01-19 00:34
@gustavottc I just noticed that the UMP is appearing every time that I launch the App, no matrer if I tap concent 15 time the poster keep spawning

**Comment by gustavottc** [comment] 2021-01-19 00:53
@martinpelli here are the explanation for this: https://github.com/Poing-Studios/Godot-AdMob-Android-iOS/issues/27#issuecomment-762275009

**Comment by gustavottc** [comment] 2021-01-19 00:54
so what you need to do to not appear the UMP when you are test is set ```is_test_europe_user_consent```to ```false```
