### ISSUE TITLE
[BUG] Can't export iOS project on Windows

### ISSUE THREAD

**Issue by Luminarcy** [Poing-Studios/Godot-AdMob-Android-iOS#72] opened 2021-05-17 11:11 UTC
**Describe the bug**
Can't export iOS project on Windows

**To Reproduce**
1. Go to Project->Export
2. Export iOS project to new folder

**Expected behavior**
Project should export without errors

**Screenshots**
![Godot_v3 3-stable_win64_IHZczzvnnt](https://user-images.githubusercontent.com/42573485/118479392-a37ee580-b719-11eb-8b6f-f9d96da8b4db.png)

**Comment by gustavottc** [comment] 2021-05-17 11:16
Hi! @Luminarcy please do these steps:

1. Delete all the content inseide `ios/plugins/admob/lib`
2. Download this `.zip`: https://github.com/Poing-Studios/Godot-AdMob-Android-iOS/releases/download/iOS_v3.3%2B/googlemobileadssdkios.zip
3.  Extract the content in `googlemobileadssdkios.zip` into `res://ios/plugins/admob/lib`

If doesn't work please let me know

**Comment by Luminarcy** [comment] 2021-05-17 11:22
Hello, @gustavottc 🙂 I've done these steps. I've got the same error messages.

**Comment by gumaciel** [comment] 2021-05-17 11:29
Please do this:

1. Go to `admob.gdip` and delete these lines: https://github.com/Poing-Studios/Godot-AdMob-Android-iOS/blob/master/ios/plugin/admob/config/admob.gdip#L9-L15
2. After exported, do this: Import the following frameworks into your Xcode project: 
```
GoogleAppMeasurement.framework
GoogleMobileAds.framework
GoogleUtilities.xcframework
nanopb.xcframework
PromisesObjC.xcframework
UserMessagingPlatform.framework
```
![image](https://user-images.githubusercontent.com/20030153/118481501-f04ac800-b6e9-11eb-99ed-b4d2be48de91.png)
![image](https://user-images.githubusercontent.com/20030153/118481521-f50f7c00-b6e9-11eb-9356-a779123b88f0.png)

**Comment by gumaciel** [comment] 2021-05-17 11:30
Oh, but you are trying to export on Windows, maybe this is the cause why is not working

**Comment by Luminarcy** [comment] 2021-05-17 11:36
Thank you! I'll try your solution.

**Comment by Luminarcy** [comment] 2021-05-17 14:58
Yes, this works, thank you!

**Comment by gumaciel** [comment] 2021-06-04 03:12
Hey @Luminarcy , i will close the issue because i tested on my Windows computer and it's working normally the export and it seems you got it work.

Any problem you can re-open the issue or create another one, thank you for using our plugin!

**Closed by gumaciel** 2021-06-04 03:12 UTC
Labels: bug
